### ISSUE TITLE
Set focus to the input link textbox

### ISSUE THREAD

**Issue by thith** [michelson/dante2#182]
1. Select a text
2. Click the Link button to convert it to a link

There are 2 problems.
1. Ihe background of the text input is white, the text color is also white, it is not possible to read. I am using Chrome on MacOS. I manage to fix it by the following CSS.
```css
.dante-menu-input {
  background-color: transparent!important;
}
```
2. It does not auto set focus to the input link text box, which confuses user. Because they dont see the cursor blink it just looks like a black bar. This happen for both sticky and non-stick bar.
![image](https://user-images.githubusercontent.com/3256373/67156835-c256a380-f34d-11e9-9a82-c7e583f34a2b.png)
