### ISSUE TITLE
Sticker toolbar does not disappear when user click outside the dante editor

### ISSUE THREAD

**Issue by thith** [michelson/dante2#183]
When the sticky toolbar is on, if I click on the space outside of the dante editor, the toolbar does not disappear. If I click on the dante editor, it does disappear.

Expect: I should disappear when I click on any place inside the document.
Note: the non-stick toolbar work as expected.

In addition, please set the z-index of sticky toolbar to something big, and let user specify its top.
My current hack.
```css
#dante-menu.dante-sticky-menu {
  /* change some style to avoid confict with the appbar */

  /* the appbar z-index is 1100 */
  z-index: 1200;
  top: 50px!important;
  text-align: center;
}
```
